### PR TITLE
issue 61 fix

### LINKED ISSUE #61: Oak Resin shows as two different items
image

Steps to reproduce:
1. Go to the Alphabetical Tab
2. Search for `Oak Resin`

Expected Result:

There should be one card for Oak Resin with two bundles listed.

Observed Result:

There are two cards for Oak resin with one bundle listed each.

### PR DESCRIPTION
**Pull request by surette**
Removed duplicate oak resin entry, added bundle 25 to original oak resin, adjusted ids.

Closes #61 .

### CODE REVIEW

**Comment by kihashi** [comment]
Thanks for the contribution!

I'm going to go ahead and merge this change, but I probably won't deploy it to the live site until I have some more changes. The saved data is tied to item IDs, so any change to item ids would invalidate a current users saved data.

**Comment by surette** [comment]
I was actually unsure about whether I should adjust the IDs or leave them, for exactly that reason—wasn't sure what (if anything) they controlled. Let me know if you'd like me to just revert them back to the old IDs.

**Comment by kihashi** [comment]
Yeah. I think that would be better. It doesn't really hurt anything to have a gap in item IDs.

Also, as a tip for the future, this probably would have been better done as 3 commits-- one for each thing. It would make reverting any one piece of it easier. Then when I merge it, I can either merge commit, squash, or rebase as appropriate.

**Comment by surette** [comment]
Sounds good, sorry about that!

**Comment by kihashi** [comment]
No worries! I appreciate the help! I don't have as much time to work on stuff like this as I would like, so any help that I get is awesome.

**Comment by surette** [comment]
Totally, I finally got around to playing Stardew recently and I've been really appreciating the site, so figured I'd see what issues were open :)

**Pull request merged**
